server:
  port: 8082
#  servlet:
#    context-path: /api/v1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_userservice
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  application:
    name: USER-SERVICE

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-05594919.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oaa45cyabn1vT5GP5d7
            client-secret: dVpcZbqjwRmr15l5JwW6PgiOPbWrndoYqjE9q92k
        provider:
          okta:
            issuer-uri: https://dev-05594919.okta.com/oauth2/default






  config:
    import: optional:configserver:http://localhost:8087

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      default-Zone: http://localhost:8761/eureka

#    management.endpoints.web.exposure.include=*
management:
  health:
    circuit-breakers:
      enable: true
  endpoints:
    web:
      exposure:
        include: "*"



  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumeBufferSize: 10
        FailuareRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationINOpenState: 6s
        permittedNumberOfCallesInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instance:
      ratingHotelService:
        max-attempt: 3
        wait-duration: 2s

  ratelimiter:
    instance:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 0s

okta:
  oauth2:
    issuer: https://dev-05594919.okta.com/oauth2/default
    audience: api://default
